---
- name: Linux OS patching
  hosts: demo
  become: true
  become_user: root
  tasks:
    - name: Update RHEL/CentOS
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Update Ubuntu
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update Debian
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: Update SUSE
      community.general.zypper:
        name: '*'
        state: latest
      when: ansible_os_family == "Suse"
    
