---
- name: Linux OS patching
  hosts: demo
  become: true
  tasks:
    - name: Precheck
      shell: if ps -eaf | egrep 'apache|http'|grep -v grep > /dev/null ;then echo 'Service are runing' ;else 'Service are not running' ; fi
      ignore_errors: yes
      register: app_service_check
    - name: If Service is running abort the Patch
      fail: msg="{{ inventory_hostname }} have running application. So please stop the application and then attempt to patch"
      when: app_service_check.stdout == "service is running"
      ignore_errors: yes
    - name: Start Updating patch for RHEL
      yum:
        name: "*"
        state: latest
        when: app_service_check.stdout == "Service are not running" and ansible_distribution == 'RedHat'
        register: yum_rhel
    - name: Start updating patch for Ubuntu and Debian
      apt:
        name: "*"
        state: latest
        when: app_service_check.stdout == "Service are not running" and ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
        register: apt_ubuntu
    - name: Starting updating patch for SUSE
      community.general.zypper:
        name: "*"
        state: latest
        when: app_service_check.stdout == "Service are not running" and ansible_distribution == 'SLES'
        register: zypper_suse
    - name: Update is completed. Requited reboot or not
      shell: KERNEL_NEW=$(rpm -q --last kernel |head -1 | awk 'print $1' | sed 's/kernel-//'); KERNEL_NOW=$(uname -r); if [[ $KERNEL_NEW != $KERNEL_NOW ]]; then echo "reboot_needed"; else echo "reboot_not_needed"; fi
      ignore_errors: yes
      register: reboot_required
    - name: restart system
      command: shutdown -r +1 "Rebooting"
      async: 0
      poll: 0
      when: reboot_required.stdout == " reboot_needed"
      register: reboot_started
      ignore_errors: yes
    - name: Pause for 300 seconds
      pause:
        min: 5
    - name: Check If connecting to SSH
      local_action:
        module: wait_for
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 15
        timeout: 300
        state: started
        when: reboot_starter|changed
