---
- name: Create users in the host node
  hosts: demo
  become: true
  tasks:
    - name: Create users in differen hosts
      user:
        name: ansible
        home: /home/ansible
    - name: Updating password for Users
      user:
        name: ansible
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"

